### ISSUE TITLE
Error during eval - can't find tokenizer

### ISSUE THREAD

**Issue by salfamusic** [thu-coai/HINT#1]
Hello,

I am getting the follower error when trying to run the eval:

```
Traceback (most recent call last):
  File "./eval.py", line 2, in <module>
    from tokenizer import SimpleTokenizer, PretrainedTokenizer
ModuleNotFoundError: No module named 'tokenizer'
```

I have searched the repo and cannot find a module named tokenizer. So I imagine this must come from one of the dependencies (probably the transformers dep?).

Can you help out? Thanks

**Comment by StevenTang1998** [comment]
The same problem here. Do you solve it?

**Comment by 1245244103** [comment]
> Hello,
> 
> I am getting the follower error when trying to run the eval:
> 
> ```
> Traceback (most recent call last):
>   File "./eval.py", line 2, in <module>
>     from tokenizer import SimpleTokenizer, PretrainedTokenizer
> ModuleNotFoundError: No module named 'tokenizer'
> ```
> 
> I have searched the repo and cannot find a module named tokenizer. So I imagine this must come from one of the dependencies (probably the transformers dep?).
> 
> Can you help out? Thanks

I have the same problem.Do you solve it?

**Comment by zhenzliu** [comment]
hello , i have another problem,when i bash finetune.sh, finetune.py not run (i add some print orders in finetune.py,but no print).
are there some issues that i neglect？
thanks for your help!

**Comment by 1245244103** [comment]
> hello , i have another problem,when i bash finetune.sh, finetune.py not run (i add some print orders in finetune.py,but no print).
> are there some issues that i neglect？
> thanks for your help!

你是跑完fineune.py没反应？

**Comment by zhenzliu** [comment]
> > hello , i have another problem,when i bash finetune.sh, finetune.py not run (i add some print orders in finetune.py,but no print).
> > are there some issues that i neglect？
> > thanks for your help!
> 
> 你是跑完fineune.py没反应？

是的，finetune.py没有运行起来

**Comment by 1245244103** [comment]
> > > hello , i have another problem,when i bash finetune.sh, finetune.py not run (i add some print orders in finetune.py,but no print).
> > > are there some issues that i neglect？
> > > thanks for your help!
> > 
> 
> > 你是跑完fineune.py没反应？
> 
> 是的，finetune.py没有运行起来

你huggingface的bart_model下载下来了吗？不然的话，那个命令的model_name_path得改一下

**Comment by zhenzliu** [comment]
![1](https://user-images.githubusercontent.com/87860116/133361071-f444ef6f-f782-4fae-aff7-1810c339b1c1.png)
我下载下来了

**Comment by 1245244103** [comment]
> ![1](https://user-images.githubusercontent.com/87860116/133361071-f444ef6f-f782-4fae-aff7-1810c339b1c1.png)
> 我下载下来了
唔，你试着挂一下vpn？我好像遇到过几次没反应的情况，但我终端走代理之后，就没遇到过了

**Comment by Zhengpeng-Guo** [comment]
> 你好，
> 
> 尝试运行 eval 时出现跟随者错误：
> 
> ```
> Traceback (most recent call last):
>   File "./eval.py", line 2, in <module>
>     from tokenizer import SimpleTokenizer, PretrainedTokenizer
> ModuleNotFoundError: No module named 'tokenizer'
> ```
> 
> 我搜索了 repo，但找不到名为 tokenizer 的模块。所以我想这一定来自依赖项之一（可能是变压器 dep？）。
> 
> 你能帮忙吗？谢谢



> 你好，
> 
> 尝试运行 eval 时出现跟随者错误：
> 
> ```
> Traceback (most recent call last):
>   File "./eval.py", line 2, in <module>
>     from tokenizer import SimpleTokenizer, PretrainedTokenizer
> ModuleNotFoundError: No module named 'tokenizer'
> ```
> 
> 我搜索了 repo，但找不到名为 tokenizer 的模块。所以我想这一定来自依赖项之一（可能是变压器 dep？）。
> 
> 你能帮忙吗？谢谢

I have the same problem, did you solve it please?

**Comment by Zhengpeng-Guo** [comment]
> Hello,
> 
> I am getting the follower error when trying to run the eval:
> 
> ```
> Traceback (most recent call last):
>   File "./eval.py", line 2, in <module>
>     from tokenizer import SimpleTokenizer, PretrainedTokenizer
> ModuleNotFoundError: No module named 'tokenizer'
> ```
> 
> I have searched the repo and cannot find a module named tokenizer. So I imagine this must come from one of the dependencies (probably the transformers dep?).
> 
> Can you help out? Thanks

I have the same problem, did you solve it please?

**Comment by tianxiexiaozhu77** [comment]
您好，非常抱歉打扰您。在运行您的程序的时候，出现问题cannot import name 'SimpleTokenizer' from 'tokenizer'。cannot import name 'PretrainedTokenizer' from 'tokenizer'。PretrainedTokenizer和SimpleTokenizer，是否漏传了呢？如果是可否更新一下呢？打扰了! 祝：科研顺利，一切都好。

**Comment by tianxiexiaozhu77** [comment]
> Hello,
> 
> I am getting the follower error when trying to run the eval:
> 
> ```
> Traceback (most recent call last):
>   File "./eval.py", line 2, in <module>
>     from tokenizer import SimpleTokenizer, PretrainedTokenizer
> ModuleNotFoundError: No module named 'tokenizer'
> ```
> 
> I have searched the repo and cannot find a module named tokenizer. So I imagine this must come from one of the dependencies (probably the transformers dep?).
> 
> Can you help out? Thanks

Excuse me, has your problem been solved? I have the same problem

> > Hello,
> > I am getting the follower error when trying to run the eval:
> > ```
> > Traceback (most recent call last):
> >   File "./eval.py", line 2, in <module>
> >     from tokenizer import SimpleTokenizer, PretrainedTokenizer
> > ModuleNotFoundError: No module named 'tokenizer'
> > ```

> > I have searched the repo and cannot find a module named tokenizer. So I imagine this must come from one of the dependencies (probably the transformers dep?).
> > Can you help out? Thanks
> 
> I have the same problem.Do you solve it?



> proble

Excuse me, has your problem been solved? I have the same problem

**Comment by Richar-Du** [comment]
> Hello,
> 
> I am getting the follower error when trying to run the eval:
> 
> ```
> Traceback (most recent call last):
>   File "./eval.py", line 2, in <module>
>     from tokenizer import SimpleTokenizer, PretrainedTokenizer
> ModuleNotFoundError: No module named 'tokenizer'
> ```
> 
> I have searched the repo and cannot find a module named tokenizer. So I imagine this must come from one of the dependencies (probably the transformers dep?).
> 
> Can you help out? Thanks

Replace it with the following code:
```
from utils import SimpleTokenizer
```
Because the SimpleTokenizer is defined in the eval/utils.py, and the PretrainedTokenizer isn't called.

**Comment by LiuTianSh** [comment]
> > hello , i have another problem,when i bash finetune.sh, finetune.py not run (i add some print orders in finetune.py,but no print).
> > are there some issues that i neglect？
> > thanks for your help!
> 
> 你是跑完fineune.py没反应？

你好，请问您知道最后的最优模型是存在best_tfmr下面吗？直接按照给的方式无法跑generation。
